export const GET_ERRORS="GET_ERRORS";
export const GET_LOGEDIN_USER_DATA="GET_LOGEDIN_USER_DATA";
export const GET_PRODUCTS="GET_PRODUCTS";
export const GET_CATEGORIES="GET_CATEGORIES";
export const GET_USERS="GET_USERS"